### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [gabriele-inghirami/eigenvectors_of_general_and_real_symmetric_matrices_with_eispack#1]
I suggest adding the topics `eigenvalue`, `eigenvector`, `eispack`, `linear-algebra` in the About section at https://github.com/gabriele-inghirami/eigenevectors_of_general_and_real_symmetric_matrices_with_eispack

**Comment by gabriele-inghirami** [comment]
I added `linear-algebra`, `eispack` and `eigenvalues-and-eigenvectors`.
Thanks for the suggestion.
